#import "ncurses.h"

int NC_A_BOLD = A_BOLD;

mmask_t NC_BUTTON1_PRESSED = BUTTON1_PRESSED;
mmask_t NC_BUTTON1_RELEASED = BUTTON1_RELEASED;
mmask_t NC_REPORT_MOUSE_POSITION = REPORT_MOUSE_POSITION;
mmask_t NC_ALL_MOUSE_EVENTS = ALL_MOUSE_EVENTS;
